name: S3 Sync on Push

on:
  push:
    branches:
      - main

jobs:
  sync-s3:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-west-1

      # Sync public/data to S3
      - name: Upload public/data to S3
        run: |
          cd transport2055

          if [ -d "public/data" ]; then
            for folder in public/data/*; do
              if [ -d "$folder" ]; then
                foldername=${folder#public/data/}
                echo "Syncing $folder â†’ s3://transport-2055-project/data/$foldername"
                aws s3 sync "$folder" "s3://transport-2055-project/data/$foldername" \
                  --exact-timestamps \
                  --acl public-read
              fi
            done
          else
            echo "No public/data folder found, skipping S3 sync."
            ls -la
          fi

